### ISSUE TITLE
Language issue

### ISSUE THREAD

**Issue by ktaranov** [aradianoff/recatpchacontact#15]
Hello.

I add to languages.yaml Russian translation and set language parameter in plugin settings **ru**, but language still is English (see link: http://decoupagepro.ru/kontakty)

**Comment by ktaranov** [comment]
Also how I can configure email to address? In README.md I can't find instruction (you using Email plugin: https://github.com/getgrav/grav-plugin-email)?

**Comment by Perlkonig** [comment]
There are some issues with the multilanguage support that I don't fully understand, not using those features of Grav typically. I'm looking into them. For now you can override those settings in a given page [as described in the README](https://github.com/aradianoff/recaptchacontact#usage). Or are you saying that your in-page overrides are also not working?

Also, you can set the email address directly in the languages file, but it makes more sense to define that on a given page, [as described in the README](https://github.com/aradianoff/recaptchacontact#usage).
