### ISSUE TITLE
Cosmetic issues with Bootstrap theme

### ISSUE THREAD

**Issue by davidzou2131** [aradianoff/recatpchacontact#16]
![horizontalformissue](https://cloud.githubusercontent.com/assets/8455302/13552413/a2480c38-e3b5-11e5-869e-39922ef25aca.png)

The `form-horizontal` class applied to the `form` causes negative padding to the fieldsets and displays 15px left of the container. This is only an issue if the [Bootstrap theme](https://github.com/getgrav/grav-theme-bootstrap) is used or Bootstrap css is included in the page.

Consider removing `class="form-horizontal"` unless you actually want a [horizontal form](https://getbootstrap.com/css/#forms-horizontal).

**Comment by Perlkonig** [comment]
Yeah. Not sure why that's there. I'll submit a pull request. I don't see a problem.
