### ISSUE TITLE
Languages Override Not Working

### ISSUE THREAD

**Issue by ghost** [aradianoff/recatpchacontact#18]
I'm using the new GRAV Beta ... suggestions?

**Comment by Perlkonig** [comment]
Can you tell us a little more? Just changing the `default_lang` isn't necessarily enough. If your blog itself is multilingual, and your base language is `en`, then changing the `default_lang` to `it` won't change it. 

I'm a new maintainer here and don't use Grav's multilingual features, but if you can give us some more details, I'll see what we can do.
