### ISSUE TITLE
grav-plugin-form compatibility

### ISSUE THREAD

**Issue by haviladev** [aradianoff/recatpchacontact#19]
I dont get if this plugin is grav-plugin-simple_contact exclusive or if it will work with grav-plugin-form?

**Comment by Perlkonig** [comment]
Looking at the code, I don't see any dependencies. I think "based on" in the README just means the author used that as a start off point. I only have `grav-plugin-form` installed and everything works just fine. I'm pretty sure it's standalone. Please open a new issue if you install it and it doesn't work as expected.
