### ISSUE TITLE
Please use email plugin

### ISSUE THREAD

**Issue by GuLinux** [aradianoff/recatpchacontact#26]
Hi,
I would like to use your plugin, but since I have grav in a docker container, it simply can't work with a local sendmail.
I installed the email plugin and configured it correctly (I tried the "test via cli") and everything works, but I noticed that recaptcha contact doesn't use it, and instead sends emails via the php "mail" function.
Could you please use the email plugin instead?
This would really add a lot of flexibility, since you can configure a huge variety of smtp servers with it.
Thanks
Marco

**Comment by bassplayer7** [comment]
@GuLinux thanks for reaching out on this! I have very good news for you. The PR (#25) that I _just_ merged moments ago defaults to the Grav Email plugin. As you are probably aware, this plugin simply used the `mail()` PHP built-in function, which leaves a lot to be desired. 

As of version 2, it now uses the Grav Email plugin if it is enabled. So go ahead and update, or install if you removed it, this plugin and let us know if you run into any trouble.

**Comment by GuLinux** [comment]
Just tried.. thank you very much! Works perfectly :)
