### ISSUE TITLE
Translation help wanted

### ISSUE THREAD

**Issue by bassplayer7** [aradianoff/recatpchacontact#27]
We were excited to release version 2 of this plugin this morning. It brings many enhancements that will hopefully increase it's usage. Part of that, however, was the addition of some admin panel integration. With that, we are need some additional translations done. 

Take a look at the [updated file](https://github.com/aradianoff/recaptchacontact/blob/master/languages.yaml) and notice that the `RECAPTCHACONTACT.ADMIN` needs to be done in **German**, **French**, **Spanish**, **Italian**, and **Russian**.

@iusvar, @Sommerregen, and @ktaranov: are you willing to take a minute to help with this?

**Comment by ghost** [comment]
I just made the pull for the Italian language

**Comment by Sommerregen** [comment]
German translation done, too!

**Comment by ktaranov** [comment]
Add Russian translation: https://github.com/aradianoff/recaptchacontact/pull/32

**Comment by bassplayer7** [comment]
You guys are great! Thank you for your assistance.
