### ISSUE TITLE
Form not showing

### ISSUE THREAD

**Issue by ghost** [aradianoff/recatpchacontact#36]
Since Grav 1.1.16 the contact form is not shown. Tested also with clean install, but nothing.

Edit: Workaround -> set up a manual position

**Comment by bassplayer7** [comment]
Thanks for reporting this issue. I will take a look.

**Comment by Globegitter** [comment]
Just tested on Grav 1.2.4 entirely through the Admin panel (Admin v1.4.2) and also not showing up for me on a fresh install on a new, otherwise empty page.

**Comment by douglasgough** [comment]
Also seeing no form on page using default template. Frontmatter is configured correctly.
Grav 1.2.4

**Comment by bassplayer7** [comment]
Sorry, I haven't been available to fix this. If you anyone wants to put up a PR, that'd be great, otherwise, I'll try to keep this on my radar to get it dealt with.

**Comment by BartoszBartniczak** [comment]
Possible solution:
https://github.com/aradianoff/recaptchacontact/pull/38

Waiting for approval.

**Comment by Perlkonig** [comment]
New release pushed. Please reopen if you still have problems. Thanks, @BartoszBartniczak .
