### ISSUE TITLE
Contact Form Doesn't Display on Modulars 

### ISSUE THREAD

**Issue by bassplayer7** [aradianoff/recatpchacontact#5]
I have been able to successfully add and use the contact form on standard pages, but it does not display on pages with modular content. In looking through the code, it looks like this may simply be not-yet-implemented. If that is the case, would this be a feature that is currently on the roadmap? If not, is there a technique that I can apply to add that to my modular page? 

I haven't spent a huge amount of time with Grav, but am quite sure I will be spending more time with it, and may be able to develop this myself. However, due to my current schedule, I suspect it would be awhile.

**Comment by aradianoff** [comment]
I updated the code so that it works in modular pages now. It will be available in the next release (hopefully sometime tomorrow). :smile:

**Comment by bassplayer7** [comment]
Wow! Wonderful: thank you for working on that.

**Comment by aradianoff** [comment]
Done! New release. Should be available in the GPM soon I guess.  Be sure to check it out. :smile: and if you find any bugs tell me.

**Comment by bassplayer7** [comment]
I certainly will. Thank you again. I created my own template to supplement but will be able to go back to just using modulars. I'm new to Grav so I wasn't able to just roll a pull request. I hope over the next few months I'll be able to take more time to dedicate to it. 

Sent from my iPhone

On Sunday, Aug 30, 2015 at 8:56 AM, aRadianOff notifications@github.com, wrote:

Done! New release. Should be available in the GPM soon I guess. Be sure to check it out.  and if you find any bugs tell me.
